FROM node:22-alpine
RUN apk add --no-cache dumb-init
WORKDIR /usr/src/app
COPY ./compras/package*.json ./
RUN npm install --omit=dev
COPY ./compras .
COPY ./shared/config ./config
COPY ./shared/db ./db
COPY ./shared/middlewares ./middlewares
COPY ./shared/models ./models
COPY ./shared/requests ./requests
COPY ./shared/utils ./utils
COPY ./shared/integrations ./integrations
ENV NODE_ENV=production
EXPOSE 80
ENTRYPOINT ["dumb-init","--"]
CMD ["node","index.js"]
